<a href="https://colab.research.google.com/github/openlearnx/Free-Training-program-on-Artificial-Intelligence-/blob/master/05_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x=np.arange(15)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
y=np.arange(15).reshape(5,3)

In [ ]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [ ]:
x=np.array([1,2,3,4,5])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x=np.arange(10)

In [ ]:
y=np.array([2,5,4,3,2,1,7,3,1,5])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y

array([2, 5, 4, 3, 2, 1, 7, 3, 1, 5])

In [ ]:
x+y

array([ 2,  6,  6,  6,  6,  6, 13, 10,  9, 14])

In [ ]:
x*y

array([ 0,  5,  8,  9,  8,  5, 42, 21,  8, 45])

In [ ]:
x/y

array([0.        , 0.2       , 0.5       , 1.        , 2.        ,
       5.        , 0.85714286, 2.33333333, 8.        , 1.8       ])

In [ ]:
x-y

array([-2, -4, -2,  0,  2,  4, -1,  4,  7,  4])

In [ ]:
np.sin(np.pi/2)

1.0

In [ ]:
np.cos(0)

1.0

In [ ]:
np.cos(np.pi/2)

6.123233995736766e-17

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.exp(-1j)

(0.5403023058681398-0.8414709848078965j)

In [ ]:
x.sum()

45

In [ ]:
x.max()

9

In [ ]:
x.min()

0

In [ ]:
x.mean()

4.5

In [ ]:
x=np.arange(12).reshape(4,3)

In [ ]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
x.sum(axis=0)

array([18, 22, 26])

In [ ]:
x.sum(axis=1)

array([ 3, 12, 21, 30])

In [ ]:
x.min(axis=0)

array([0, 1, 2])

In [ ]:
x.shape

(4, 3)

In [ ]:
x=20
y=30

In [ ]:
bin(20)

'0b10100'

In [ ]:
np.bitwise_and(x,y)

20

In [ ]:
np.char.add(["hello"], ["world"])

array(['helloworld'], dtype='<U10')

In [ ]:
np.char.multiply("hello", 3)

array('hellohellohello', dtype='<U15')

In [ ]:
np.char.upper("Hello")

array('HELLO', dtype='<U5')

In [ ]:
np.char.lower("HELLOW")

array('hellow', dtype='<U6')

In [ ]:
np.char.replace("Hello world", "Hello" , "Hi")

array('Hi world', dtype='<U8')

In [ ]:
x=np.array([5.36,5.3354,4.62,9.08])

In [ ]:
np.around(x)

array([5., 5., 5., 9.])

In [ ]:
x=10
y=20

In [ ]:
np.add(x,y)

30

In [ ]:
np.subtract(x,y)

-10

In [ ]:
x=np.arange(50)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
np.savetxt("out.txt",x)